AWSTemplateFormatVersion: "2010-09-09"
Description: An access key for rule for age of keys
Parameters:
  MaxAccessKeyAge:
    Description: Access key max age
    Type: String
Resources:
  AccessKeysRotated:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: access-keys-rotated
      InputParameters:
        maxAccessKeyAge: !Ref MaxAccessKeyAge
      Source:
        Owner: AWS
        SourceIdentifier: ACCESS_KEYS_ROTATED
