AWSTemplateFormatVersion: "2010-09-09"
Description: Codebuild config rules
Resources:
  CodeBuildProjectEnvVarAWSCredCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: codebuild-project-envvar-awscred-check
      Source:
        Owner: AWS
        SourceIdentifier: CODEBUILD_PROJECT_ENVVAR_AWSCRED_CHECK
  CodeBuildProjectSourceRepoURLCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: codebuild-project-source-repo-url-check
      Source:
        Owner: AWS
        SourceIdentifier: CODEBUILD_PROJECT_SOURCE_REPO_URL_CHECK
