AWSTemplateFormatVersion: "2010-09-09"
Description: The root stack for all config rules
Resources:
  IAMRules:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BlockedActionPatterns: kms:*
      TemplateURL: iam-rules.yaml
  AccessKeyRule:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        MaxAccessKeyAge: 90
      TemplateURL: access-key-rule.yaml
  AccountPartOfOrganizations:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: account-part-of-organizations-rule.yaml
  ACMCertificateExpirationCheck:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DaysToExpiration: 60
      TemplateURL: acm-certificate-expiration-check-rule.yaml
