AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack for config resources
Resources:
  ConfigSetup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: setup/setup.yaml
  ConfigRules:
    DependsOn:
      - ConfigSetup
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rules/root.yaml
